### ISSUE TITLE
Schedule Builds according to Nix Dependencies

### ISSUE THREAD

**Issue by lorenzleutgeb** [nix-community/buildbot-nix#138]
[ngi-nix/ngipkgs](https://github.com/ngi-nix/ngipkgs/) will migrate to buildbot ngi-nix/ngipkgs#200. It's a monorepo that contains derivations for various NGI Projects. They all somehow consume nixpkgs, but it is rare that NGI Projects depend on each other. Thus, when viewed as a DAG of derivations, it looks roughly like this:

![Untitled drawing](https://github.com/Mic92/buildbot-nix/assets/542154/24e32d31-0835-4cbb-87f8-17ece47681fb)

Ignoring references to nixpkgs (in the build context: assume it's cached), the repo decomposes into multiple weakly connected components. Now, my thesis is that (especially if you have multiple workers on multiple machines), it'd be beneficial not to create one build per derivation, but rather one build per weakly connected component of derivations. With the above diagram, you would not get 9 builds but 3.

I have implemented such an analysis in Python using [NetworkX](https://networkx.org/) on top of `nix-eval-jobs` that generates a build matrix for GitHub Actions, see [`.../build_matrix/main.py`](https://github.com/ngi-nix/ngipkgs/blob/425f4bcd379c803e4562dc4643b8bbddf9079bfe/pkgs/by-name/build-matrix/src/build_matrix/main.py). This results in workflows like the following:

 * [Run 8926962816](https://github.com/ngi-nix/ngipkgs/actions/runs/8926962816): With cache, just builds one package (and sanity checks).
 * [Run 8744345769](https://github.com/ngi-nix/ngipkgs/actions/runs/8744345769): Without cache (for testing purposes), fans out to many jobs, but note that they are not strictly one per derivation, e.g. " build kbin, kbin-frontend-0.0.1, kbin-0.0.1" is a build for 3 derivations.

Since I am not (yet) a user of buildbot-nix, I might be missing something, but...
 * AFAIK buildbot-nix does not make such an analysis. Is that on purpose, i.e. do you think there's no benefit in doing that? If yes, I'd be curious to learn why?
 * Is this something you would like to see upstreamed to buildbot-nix? If yes, should it be hidden behind some configuration? Which?

**Comment by Mic92** [comment]
Back when I started buildbot-nix, there was no `inputDerivations` in nix-eval-jobs so this analysis would have been harder. I guess I didn't needed this feature as much because my main concern was to have a fast CI for NixOS machines and inter-dependencies was that much of a factor. How do you connect different projects? Buildbot actually support multiple source triggers the same hydra does it, but with flakes everything is kind of pinned.

So here is my constraints:

* building all derivations individually will be likely too slow so we probably need to keep it as coarse grained as only building flake attributes -> but this is what you do as well.
* if we group flake attributes, we should probably still maintain separate build logs because otherwise it becomes quite hard to see errors in long logs. Buildbot actually support many text outputs per build step.

Buildbot also allows some control regarding scheduling in python code, so even if it's displayed as separated build step it could still internally following the ordering that you propose.

All in all it would be probably to discuss this more in detail in our matrix channel:

https://matrix.to/#/#buildbot-nix:thalheim.io

**Comment by lorenzleutgeb** [comment]
Just had a chat with @Mic92 and we agreed on not mapping multiple derivations to one build, but keep the 1:1 mapping that exists currently. Instead, model the dependency graph of derivations in buildbot scheduling directly. Essentially we inform buildbot with the dependency information that Nix already has, and let jobs wait for dependencies.

In order for this to work nicely, all actual builders (in the Nix sense, the machines that do `nix build`, might be the worker, or might be a remote builder) would have to have  access to a shared Nix store or binary cache for this to make sense. This could be resolved by using the grouping I sketched above to map builds to workers (or builders in the Nix sense). We decided to postpone this, and first get dependency-based scheduling to work on its own.

**Comment by lorenzleutgeb** [comment]
There's are two interesting scheduling concepts in buildbot:
 - [Dependent Scheduler](https://docs.buildbot.net/current/manual/configuration/schedulers.html#sched-Dependent)
 - [Triggerable Scheduler](https://docs.buildbot.net/current/manual/configuration/schedulers.html#sched-Triggerable)

At a first glance, Triggerable Scheduler seems to be strictly better (?!). I'll look at this into more detail soon, but wanted to share as early as possible.

**Comment by Mic92** [comment]
We are currently using the [Triggerable Scheduler](https://docs.buildbot.net/current/manual/configuration/schedulers.html#sched-Triggerable) because it allows to create dynamic pipelines.

**Comment by MagicRB** [comment]
Fixed by #77 I think.

**Comment by lorenzleutgeb** [comment]
I don't understand. #77 is an issue, not a PR. It refers to a duplicate at #224 which apparently got resolved by merge of #255. So you probably mean that #138 was fixed by #255? If so, I'd appreciate if you could give me a pointer to see that. #255 talks about retries.

**Comment by Mic92** [comment]
https://github.com/nix-community/buildbot-nix/pull/255 also introduces a build order between flake attributes: https://github.com/nix-community/buildbot-nix/blob/main/buildbot_nix/__init__.py#L462
