### ISSUE TITLE
Cache failed builds

### ISSUE THREAD

**Issue by MagicRB** [nix-community/buildbot-nix#224]
Currently if a build fails buildbot-nix will attempt to rebuild it every time it pops up in an evaluation, which is wasteful, unless the failure was temporary. The lix [fork](https://git.lix.systems/lix-project/buildbot-nix) of `buildbot-nix` already has this, so we can just pull those changes into upstream (this repository).

**Comment by Mic92** [comment]
The lix fork creates build steps for every derivation, I saw. I think this might be ok for packages but can get really slow for NixOS configuration where we have to build a lot of small derivations at least it was in hercules-ci.

**Comment by MagicRB** [comment]
Oh yeah that is a horrible idea, I was thinkimg about caching the failures of toplevel derivations.

**Comment by MagicRB** [comment]
@Mic92 as far as I can tell, their failed build caching doesn't work across builds, https://git.lix.systems/lix-project/buildbot-nix/src/branch/main/buildbot_nix/__init__.py#L180 I don't see a persistent global failed build cache anywhere, so we cannot pull anything afaict

**Comment by puckipedia** [comment]
> The lix fork creates build steps for every derivation, I saw.

If this were the case, any build even remotely dependent on nixpkgs would create thousands of build steps, which would bog down any buildbot instance instantly. [Any evaluation done by our buildbot instance](https://buildbot.lix.systems/#/builders/1/builds/4650) also shows this isn't how it works. We've just replaced the part of the scheduler that registers all builds in one go with one that only schedules a build once the builds it depends on succeed.

**Comment by Mic92** [comment]
I cannot see the website unfortunately. There seems to be an issue with the authentication:

> You do not have the can-perform-mutations buildbot role

**Comment by puckipedia** [comment]
..I entirely forgot we put the entire site behind ACLs, as a temporary thing until we got buildbot-native ACLs working, and then kinda forgot to write the buildbot ACLs. Sorry! Attached a screenshot.
<details>
<summary>loooong screenshot</summary>

![lix-eval](https://github.com/user-attachments/assets/0c440fb5-ab21-4bbf-8952-898c3776d45d)

</details>

**Comment by MagicRB** [comment]
@puckipedia I must be missing something, because your code does trigger a scheduler per each derivation, as can be seen in the logs by the flood of `Scheduling` which are coming from [here](https://git.lix.systems/lix-project/buildbot-nix/src/branch/main/buildbot_nix/__init__.py#L196) and then right after you [trigger](https://git.lix.systems/lix-project/buildbot-nix/src/branch/main/buildbot_nix/__init__.py#L200) a scheduler to do the actual build of that one derivation.

**Comment by puckipedia** [comment]
that's not "every derivation"; otherwise I'd say that this repo's buildbot-nix in fact also builds "every derivation". Compare:

<details>
<summary>also a long screenshot, though not quite as long</summary>

![https://buildbot.thalheim.io/#/builders/4/builds/333](https://github.com/user-attachments/assets/59a8b0db-729c-4365-9b8d-394998e47e5d)

</details>

I'd say that the qemu dependency itself would fill like twenty pages if every derivation was scheduled independently :)

(also, -29 pending builds?)

**Comment by puckipedia** [comment]
And mind you, the "Scheduling" logic there is just replicating what the Buildbot `Trigger` class does. However, it does so entirely dynamically, rather than scheduling all builds at the start of the run in `getSchedulersAndProperties`. This allows us finer control to determine _when_ a check is scheduled; and we use this to avoid CPU waste by building every check when a check it depends on fails. In this example, we avoid rebuilding Lix halfway through about 28 times, which is a huge time waster:

<details>
<summary>You know the gist by now.</summary>

![yup that's right, another screenshot of the lix buildbot, showing 28 skipped checks because a build that they all depended upon failed.](https://github.com/user-attachments/assets/d7076209-121c-440f-be4b-404c828f9061)
</detail>

**Comment by MagicRB** [comment]
> And mind you, the "Scheduling" logic there is just replicating what the Buildbot `Trigger` class does. However, it does so entirely dynamically, rather than scheduling all builds at the start of the run in `getSchedulersAndProperties`. This allows us finer control to determine _when_ a check is scheduled; and we use this to avoid CPU waste by building every check when a check it depends on fails. In this example, we avoid rebuilding Lix halfway through about 28 times, which is a huge time waster:
> You know the gist by now.
> 
> ![yup that's right, another screenshot of the lix buildbot, showing 28 skipped checks because a build that they all depended upon failed.](https://private-user-images.githubusercontent.com/488734/353603027-d7076209-121c-440f-be4b-404c828f9061.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNzA5MjMsIm5iZiI6MTcyMjM3MDYyMywicGF0aCI6Ii80ODg3MzQvMzUzNjAzMDI3LWQ3MDc2MjA5LTEyMWMtNDQwZi1iZTRiLTQwNGM4MjhmOTA2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQyMDE3MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NjJhMGRiZGM3MTM2ZmM0ZmI0ZTczMWU3NjEzZGVhODM2MjZmMTY4MjBjOWRhNTJhYjhmYzVmNzU2ZDY2ZjBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.t3wYz8-u9F3GWyje0Rud9Bjg0kUbDJPUUSPj-SUJ5Ks)

That is very reasonable, I'll need to read more, I am slightly struggling to make sense of the code. I'll figure it out tho, thanks fir the help, I appreciate it.

**Comment by MagicRB** [comment]
Closed by #255

**Comment by puckipedia** [comment]
note that defer and async have slightly different behaviours in this case; from what i can tell, it's safe to not drive the defer and let it execute in the background; that's what is happening here
